name: Publish Docker image on merge to main

on:
  push:
    # Publish semver tags as releases.
    tags: [ 'release-v*.*.*' ]

jobs:
  build-and-publish:
  
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: src/Customer.Service
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2        
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2        
      - 
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Publish Docker image to Docker Hub
        uses: docker/build-push-action@v4.0.0
        with:     
          add_git_labels: true
          tag_with_ref: true
          context: src/Customer.Service
          push: true # push image to Docker Hub
          tags: |
            loanburger/customer-service:latest
            loanburger/customer-service:${{ github.sha }}
